eddited cloudbuild

diff --git a/root/cloudbuild.yml b/root/cloudbuild.yml
--- a/root/cloudbuild.yml
+++ b/root/cloudbuild.yml
@@ -16,8 +16,8 @@ steps:
       terraform -version || echo "Terraform not installed in this image"
       echo "gcloud version:"
       gcloud --version
-      echo "Impersonation target: ${TF_VAR_deploy_sa_email}"
-      gcloud auth print-access-token --impersonate-service-account="${TF_VAR_deploy_sa_email}" >/dev/null && echo "Impersonation OK" || echo "Impersonation FAILED"
+      echo "Impersonation target: $TF_VAR_deploy_sa_email"
+      gcloud auth print-access-token --impersonate-service-account="$TF_VAR_deploy_sa_email" >/dev/null && echo "Impersonation OK" || echo "Impersonation FAILED"
 
 # Step 2: Terraform Init + Validate
 - name: hashicorp/terraform:1.6.6
@@ -27,8 +27,8 @@ steps:
     - -c
     - |
       terraform init \
-        -backend-config="bucket=${_TF_STATE_BUCKET}" \
-        -backend-config="prefix=${_TF_STATE_PREFIX}"
+        -backend-config="bucket=$_TF_STATE_BUCKET" \
+        -backend-config="prefix=$_TF_STATE_PREFIX"
       terraform fmt -check
       terraform validate
   env:
